### ISSUE TITLE
Update footer to have consistent date on all pages

### ISSUE THREAD

**Issue by daveyvango** [RichardLaskowski/Bright-Field-Website#33]
The start date is only on a couple of pages.  Put it on every page.  Maybe figure out a way to just to include a standard footer.

**Comment by cdimoulis** [comment]
@daveyvango I would love this, but that would require a reusable template of some kind which is hard (maybe not posssible) to do with static files and no server side rendering/compilation!!!! but that would be fun to do!!!

**Comment by daveyvango** [comment]
I think if anyone can do it, it's @cdimoulis .
